# This workflow will build the MyGPTchat application
# Front end node js build
name: MyGPTchat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: npm ci
      working-directory: ./frontend
    - run: npm run build --if-present
      working-directory: ./frontend
    - run: ./post-build.sh
      working-directory: ./frontend
    - name: Push generated webpage to another repository
      uses: nkoppel/push-files-to-another-repository@1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'frontend/dist/chat.html frontend/dist/assets' 
        destination-username: 'dhiman1987'
        destination-repository: 'dhiman1987.github.io'
        commit-email: 'dhiman.talapatra@gmail.com'

    
